"""add ping_logs_hourly aggregate

Revision ID: 19d985652ed0
Revises: 840ae68f7897
Create Date: 2026-05-02 08:23:14.923692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19d985652ed0'
down_revision: Union[str, Sequence[str], None] = '840ae68f7897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ping_logs_hourly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('hour', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('avg_response_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ping_logs_hourly', schema=None) as batch_op:
        batch_op.create_index('idx_ping_hourly_device_hour', ['device_id', 'hour'], unique=True)
        batch_op.create_index('idx_ping_hourly_hour', ['hour'], unique=False)
        batch_op.create_index(batch_op.f('ix_ping_logs_hourly_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ping_logs_hourly', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ping_logs_hourly_id'))
        batch_op.drop_index('idx_ping_hourly_hour')
        batch_op.drop_index('idx_ping_hourly_device_hour')

    op.drop_table('ping_logs_hourly')
    # ### end Alembic commands ###
